# Generated by Django 5.0 on 2024-05-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0005_rename_active_driver_available_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_location", models.CharField(max_length=255)),
                ("destination_location", models.CharField(max_length=255)),
                ("distance", models.FloatField()),
                (
                    "type_of_ride",
                    models.CharField(
                        choices=[
                            ("Peak", "Peak"),
                            ("Normal", "Normal"),
                            ("Smooth", "Smooth"),
                        ],
                        default="Normal",
                        max_length=255,
                    ),
                ),
                ("base_fare", models.FloatField(blank=True, null=True)),
                ("total_received", models.FloatField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver",
                        to="user.driver",
                    ),
                ),
                (
                    "shared_with_friends",
                    models.ManyToManyField(
                        blank=True, related_name="shared_rides", to="user.myuser"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="user.myuser",
                    ),
                ),
            ],
        ),
    ]
