# Generated by Django 5.0 on 2024-05-16 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ride", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookingHistory",
        ),
    ]
