# Generated by Django 5.0 on 2024-05-16 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ride", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ride",
            old_name="extra_tips",
            new_name="distance",
        ),
    ]
