# Generated by Django 5.0 on 2024-05-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride", "0001_initial"),
        ("user", "0005_rename_active_driver_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ride_driver",
                to="user.driver",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ride_user",
                to="user.myuser",
            ),
        ),
    ]
