# Generated by Django 5.0 on 2024-05-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride", "0002_alter_ride_driver_alter_ride_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="carbonfootprint_earned",
            field=models.FloatField(default=0),
        ),
    ]
