# Generated by Django 5.0 on 2024-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride", "0002_rename_extra_tips_ride_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinghistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
