# Generated by Django 5.0 on 2024-05-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promo", "0001_initial"),
        ("user", "0005_rename_active_driver_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promo",
            name="reward_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="RedeemedPromo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="promo.promo"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redeemed_promos",
                        to="user.myuser",
                    ),
                ),
            ],
        ),
    ]
