# Generated by Django 5.0 on 2024-05-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ewallet",
            name="amount",
            field=models.FloatField(default=0.0),
        ),
    ]
