# Generated by Django 5.0 on 2024-05-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("car_model", models.CharField(max_length=100)),
                ("plate_number", models.CharField(max_length=20)),
                ("rating", models.FloatField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("service_duration", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="MyUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("phoneNumber", models.CharField(max_length=20)),
                ("profilePicture", models.ImageField(upload_to="profile_pictures/")),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True, related_name="friends_list", to="user.myuser"
                    ),
                ),
            ],
        ),
    ]
