# Generated by Django 5.0 on 2024-05-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="service_duration",
        ),
        migrations.AddField(
            model_name="driver",
            name="service_duration_year",
            field=models.IntegerField(default=0),
        ),
    ]
