# Generated by Django 5.0 on 2024-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_driver_service_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="profilePicture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
