# Generated by Django 5.0 on 2024-05-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_myuser_profilepicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
