# Generated by Django 5.0 on 2024-05-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carbonFootprint", "0002_carbonfootprint_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbonfootprint",
            name="total_distance",
            field=models.FloatField(default=0.0),
        ),
    ]
